### ISSUE TITLE
[BE] 기본 셋팅 

### ISSUE THREAD

**Issue by sokojh** [heading1/WYLSBingsu#18]
## 🔨 기능 설명
-타입스크립트 환경설정
-백엔드 monolith 아키텍쳐 구조로 폴더 구조 생성
-API 서버 폴더 생성
 
## 📑 완료 조건
- [x]  폴더구조 생성
- [x] 기본 구성 파일 추가 

## 💭 관련 Backlog
기본셋팅 - 백엔드 초기 셋팅 - 폴더구조,기본구성 추가

**Comment by kjklalala2** [comment]
세팅 문제 없이 완료하였습니다. .gitkeep은 파일 생성 후 삭제 예정입니다.

**Comment by sokojh** [comment]
> 세팅 문제 없이 완료하였습니다. .gitkeep은 파일 생성 후 삭제 예정입니다.

넵 좋습니다.

**Comment by Circlewee** [comment]
feature/#18 branch에 server라고 새로 생성된 디렉토리를 확인했습니다.
이 디렉토리가 백엔드분들이 작성할 코드가 전부 들어가는 건가요?
제안을 하나 해보자면 server는 이름이 좀 모호한 것 같아서 backend, frontend 이런식으로 명명하는 것은 어떠신가요?

**Comment by sokojh** [comment]
> feature/#18 branch에 server라고 새로 생성된 디렉토리를 확인했습니다. 이 디렉토리가 백엔드분들이 작성할 코드가 전부 들어가는 건가요? 제안을 하나 해보자면 server는 이름이 좀 모호한 것 같아서 backend, frontend 이런식으로 명명하는 것은 어떠신가요?

아 그럴수있겠네용! 디스커션에 #20 올렸습니다 !
