### ISSUE TITLE
[FE] React Router Dom 구현방법

### ISSUE THREAD

**Issue by jinux127** [heading1/WYLSBingsu#8]

**Comment by Circlewee** [comment]
## 구현 방법
1. history라이브러리 사용(Browser History Mode, react-router-dom라이브러리에서도 사용함)
2. hash를 사용하는 방법 (Hash History Mode)

## Reference
[Vanila JS에서 SPA 라우팅 시스템 구현하기](https://kdydesign.github.io/2020/10/06/spa-route-tutorial/)

**Comment by jinux127** [comment]
공부해서 정리해보죠!!
